block-list-secret-scan: []
branch: master
directory:
- .
download-external-modules: true
evaluate-variables: true
external-modules-download-path: .external_modules
framework:
- terraform
mask: []
quiet: true
secrets-history-timeout: 12h
secrets-scan-file-type: []
skip-path:
- examples
summary-position: top
